
# Hands-on Lab: API Examples
## Random User and Fruityvice API Examples


Estimated time needed: **30** minutes

## Objectives

After completing this lab you will be able to:

*   Load and use RandomUser API, using `RandomUser()` Python library
*   Load and use Fruityvice API, using `requests` Python library
*   Load and use Open-Joke-API, using `requests` Python library

The purpose of this notebook is to provide more examples on how to use simple APIs. As you have already learned from previous videos and notebooks, API stands for Application Programming Interface and is a software intermediary that allows two applications to talk to each other. 

The advantages of using APIs:
 *   **Automation**. Less human effort is required and workflows can be easily updated to become faster and more      
     productive.
 *   **Efficiency**. It allows to use the capabilities of one of the already developed APIs than to try to 
     independently implement some functionality from scratch.
 
The disadvantage of using APIs:
 *   **Security**. If the API is poorly integrated, it means it will be vulnerable to attacks, resulting in data breeches or losses having financial or reputation implications.

One of the applications we will use in this notebook is Random User Generator. RandomUser is an open-source, free API providing developers with randomly generated users to be used as placeholders for testing purposes. This makes the tool similar to Lorem Ipsum, but is a placeholder for people instead of text. The API can return multiple results, as well as specify generated user details such as gender, email, image, username, address, title, first and last name, and more. More information on [RandomUser](https://randomuser.me/documentation#intro) can be found here.

Another example of simple API we will use in this notebook is Fruityvice application. The Fruityvice API web service which provides data for all kinds of fruit! You can use Fruityvice to find out interesting information about fruit and educate yourself. The web service is completely free to use and contribute to.

## Example 1: RandomUser API
Bellow are Get Methods parameters that we can generate. For more information on the parameters, please visit this [documentation](https://randomuser.me/documentation) page.

## **Get Methods**

- get_cell()
- get_city()
- get_dob()
- get_email()
- get_first_name()
- get_full_name()
- get_gender()
- get_id()
- get_id_number()
- get_id_type()
- get_info()
- get_last_name()
- get_login_md5()
- get_login_salt()
- get_login_sha1()
- get_login_sha256()
- get_nat()
- get_password()
- get_phone()
- get_picture()
- get_postcode()
- get_registered()
- get_state()
- get_street()
- get_username()
- get_zipcode()

To start using the API you can install the `randomuser` library running the `pip install` command.

In [1]:
!pip install randomuser
!pip install pandas

Collecting randomuser
  Downloading randomuser-1.6.tar.gz (5.0 kB)
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: randomuser
  Building wheel for randomuser (setup.py) ... one
  Created wheel for randomuser: filename=randomuser-1.6-py3-none-any.whl size=5104 sha256=55561d6d3dc3eb259395551918890b25d728c6100ffd24f5bc75eeb31c458af1
  Stored in directory: /home/jupyterlab/.cache/pip/wheels/be/62/c8/71e1b48f4758ea5b78af7595d87178f628cde315a3326610ee
Successfully built randomuser
Installing collected packages: randomuser
Successfully installed randomuser-1.6
Collecting pandas
  Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (79 kB)
Collecting numpy>=1.26.0 (from pandas)
  Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in /opt/conda/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /opt/conda/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.3-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (10.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 159.5 MB/s eta 0:00:00
Downloading numpy-2.4.6-cp312-cp312-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl (16.6 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.6/16.6 MB 161.3 MB/s eta 0:00:00
Installing collected packages: numpy, pandas
Successfully installed numpy-2.4.6 pandas-3.0.3

Then, we will load the necessary libraries.

In [2]:
from randomuser import RandomUser
import pandas as pd

First, we will create a random user object, r.

In [3]:
r = RandomUser()

Then, using `generate_users()` function, we get a list of random 10 users.

In [4]:
some_list = r.generate_users(10)

In [5]:
some_list

[<randomuser.RandomUser at 0x7106c2d20da0>,
 <randomuser.RandomUser at 0x7106c2d20dd0>,
 <randomuser.RandomUser at 0x7106c2d20e00>,
 <randomuser.RandomUser at 0x7106c2d20e30>,
 <randomuser.RandomUser at 0x7106c2d20e60>,
 <randomuser.RandomUser at 0x7106c2d20e90>,
 <randomuser.RandomUser at 0x7106c2d20ec0>,
 <randomuser.RandomUser at 0x7106c2d20ef0>,
 <randomuser.RandomUser at 0x7106c2d20f20>,
 <randomuser.RandomUser at 0x7106c2d20f50>]

The **"Get Methods"** functions mentioned at the beginning of this notebook, can generate the required parameters to construct a dataset. For example, to get full name, we call `get_full_name()` function.

In [6]:
name = r.get_full_name()

Let's say we only need 10 users with full names and their email addresses. We can write a "for-loop" to print these 10 users.

In [7]:
for user in some_list:
    print (user.get_full_name()," ",user.get_email())

Aubrey Barnaby   aubrey.barnaby@example.com
Rosalyn Jones   rosalyn.jones@example.com
Aleksandra Da Silva   aleksandra.dasilva@example.com
Davut Tekelioğlu   davut.tekelioglu@example.com
Lilli Fabre   lilli.fabre@example.com
Vicky Martin   vicky.martin@example.com
Alfred Jørgensen   alfred.jorgensen@example.com
Angie Ross   angie.ross@example.com
محمدپارسا نكو نظر   mhmdprs.nkwnzr@example.com
Caroline Rasmussen   caroline.rasmussen@example.com

## Exercise 1
In this Exercise, generate photos of the random 10 users.

In [9]:
## Write your code here
for user in some_list:
    print(user.get_picture())

https://randomuser.me/api/portraits/women/36.jpg
https://randomuser.me/api/portraits/women/82.jpg
https://randomuser.me/api/portraits/women/41.jpg
https://randomuser.me/api/portraits/men/23.jpg
https://randomuser.me/api/portraits/women/87.jpg
https://randomuser.me/api/portraits/women/83.jpg
https://randomuser.me/api/portraits/men/93.jpg
https://randomuser.me/api/portraits/women/44.jpg
https://randomuser.me/api/portraits/men/74.jpg
https://randomuser.me/api/portraits/women/28.jpg

<details><summary>Click here for the solution</summary>

```python
for user in some_list:
    print (user.get_picture())
```

</details>

To generate a table with information about the users, we can write a function containing all desirable parameters. For example, name, gender, city, etc. The parameters will depend on the requirements of the test to be performed. We call the Get Methods, listed at the beginning of this notebook. Then, we return pandas dataframe with the users.

In [10]:
def get_users():
    users =[]
     
    for user in RandomUser.generate_users(10):
        users.append({"Name":user.get_full_name(),"Gender":user.get_gender(),"City":user.get_city(),"State":user.get_state(),"Email":user.get_email(), "DOB":user.get_dob(),"Picture":user.get_picture()})
      
    return pd.DataFrame(users)

In [11]:
get_users()

,Name,Gender,City,State,Email,DOB,Picture
0,Beatriz Soler,female,Gandía,Canarias,beatriz.soler@example.com,1956-12-16T19:18:16.761Z,https://randomuser.me/api/portraits/women/12.jpg
1,Willie Heuveling,female,Houten,Zeeland,willie.heuveling@example.com,1947-04-01T00:23:41.300Z,https://randomuser.me/api/portraits/women/23.jpg
2,Archie Hall,male,Blenheim,Nelson,archie.hall@example.com,1982-01-06T06:27:49.538Z,https://randomuser.me/api/portraits/men/28.jpg
3,Alix Marie,female,Montpellier,Lot,alix.marie@example.com,1951-05-07T11:56:37.895Z,https://randomuser.me/api/portraits/women/15.jpg
4,Andre Guillaume,male,Einsiedeln,Glarus,andre.guillaume@example.com,1975-02-28T23:32:16.751Z,https://randomuser.me/api/portraits/men/48.jpg
5,Benjamin Madsen,male,Sandved,Danmark,benjamin.madsen@example.com,1986-01-25T21:09:27.616Z,https://randomuser.me/api/portraits/men/32.jpg
6,Babür Akbulut,male,Kars,Adana,babur.akbulut@example.com,1979-07-25T04:23:50.823Z,https://randomuser.me/api/portraits/men/75.jpg
7,Teunisje Van Gaal,female,Groede,Gelderland,teunisje.vangaal@example.com,1954-10-07T03:39:09.047Z,https://randomuser.me/api/portraits/women/5.jpg
8,Leyla Perrin,female,Ermatingen,Genève,leyla.perrin@example.com,1949-06-30T22:48:57.137Z,https://randomuser.me/api/portraits/women/75.jpg
9,Gonzalo Castro,male,Torrente,Asturias,gonzalo.castro@example.com,1947-05-03T16:28:01.067Z,https://randomuser.me/api/portraits/men/4.jpg

In [ ]:
df1 = pd.DataFrame(get_users())

Now we have a *pandas* dataframe that can be used for any testing purposes that the tester might have.

## Example 2: Fruityvice API

Another, more common way to use APIs, is through `requests` library. The next lab, Requests and HTTP, will contain more information about requests.

We will start by importing all required libraries.

In [12]:
import requests
import json

We will obtain the [fruityvice](https://www.fruityvice.com) API data using `requests.get("url")` function. The data is in a json format.

In [13]:
data = requests.get("https://web.archive.org/web/20240929211114/https://fruityvice.com/api/fruit/all")

We will retrieve results using `json.loads()` function.

In [14]:
results = json.loads(data.text)

We will convert our json data into *pandas* data frame.

In [15]:
pd.DataFrame(results)

,name,id,family,order,genus,nutritions
0,Persimmon,52,Ebenaceae,Rosales,Diospyros,"{'calories': 81, 'fat': 0.0, 'sugar': 18.0, 'c..."
1,Strawberry,3,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
2,Banana,1,Musaceae,Zingiberales,Musa,"{'calories': 96, 'fat': 0.2, 'sugar': 17.2, 'c..."
3,Tomato,5,Solanaceae,Solanales,Solanum,"{'calories': 74, 'fat': 0.2, 'sugar': 2.6, 'ca..."
4,Pear,4,Rosaceae,Rosales,Pyrus,"{'calories': 57, 'fat': 0.1, 'sugar': 10.0, 'c..."
5,Durian,60,Malvaceae,Malvales,Durio,"{'calories': 147, 'fat': 5.3, 'sugar': 6.75, '..."
6,Blackberry,64,Rosaceae,Rosales,Rubus,"{'calories': 40, 'fat': 0.4, 'sugar': 4.5, 'ca..."
7,Lingonberry,65,Ericaceae,Ericales,Vaccinium,"{'calories': 50, 'fat': 0.34, 'sugar': 5.74, '..."
8,Kiwi,66,Actinidiaceae,Struthioniformes,Apteryx,"{'calories': 61, 'fat': 0.5, 'sugar': 9.0, 'ca..."
9,Lychee,67,Sapindaceae,Sapindales,Litchi,"{'calories': 66, 'fat': 0.44, 'sugar': 15.0, '..."
10,Pineapple,10,Bromeliaceae,Poales,Ananas,"{'calories': 50, 'fat': 0.12, 'sugar': 9.85, '..."
11,Fig,68,Moraceae,Rosales,Ficus,"{'calories': 74, 'fat': 0.3, 'sugar': 16.0, 'c..."
12,Gooseberry,69,Grossulariaceae,Saxifragales,Ribes,"{'calories': 44, 'fat': 0.6, 'sugar': 0.0, 'ca..."
13,Passionfruit,70,Passifloraceae,Malpighiales,Passiflora,"{'calories': 97, 'fat': 0.7, 'sugar': 11.2, 'c..."
14,Plum,71,Rosaceae,Rosales,Prunus,"{'calories': 46, 'fat': 0.28, 'sugar': 9.92, '..."
15,Orange,2,Rutaceae,Sapindales,Citrus,"{'calories': 43, 'fat': 0.2, 'sugar': 8.2, 'ca..."
16,GreenApple,72,Rosaceae,Rosales,Malus,"{'calories': 21, 'fat': 0.1, 'sugar': 6.4, 'ca..."
17,Raspberry,23,Rosaceae,Rosales,Rubus,"{'calories': 53, 'fat': 0.7, 'sugar': 4.4, 'ca..."
18,Watermelon,25,Cucurbitaceae,Cucurbitales,Citrullus,"{'calories': 30, 'fat': 0.2, 'sugar': 6.0, 'ca..."
19,Lemon,26,Rutaceae,Sapindales,Citrus,"{'calories': 29, 'fat': 0.3, 'sugar': 2.5, 'ca..."
20,Mango,27,Anacardiaceae,Sapindales,Mangifera,"{'calories': 60, 'fat': 0.38, 'sugar': 13.7, '..."
21,Blueberry,33,Rosaceae,Rosales,Fragaria,"{'calories': 29, 'fat': 0.4, 'sugar': 5.4, 'ca..."
22,Apple,6,Rosaceae,Rosales,Malus,"{'calories': 52, 'fat': 0.4, 'sugar': 10.3, 'c..."
23,Guava,37,Myrtaceae,Myrtales,Psidium,"{'calories': 68, 'fat': 1.0, 'sugar': 9.0, 'ca..."
24,Apricot,35,Rosaceae,Rosales,Prunus,"{'calories': 15, 'fat': 0.1, 'sugar': 3.2, 'ca..."
25,Melon,41,Cucurbitaceae,Cucurbitaceae,Cucumis,"{'calories': 34, 'fat': 0.0, 'sugar': 8.0, 'ca..."
26,Tangerine,77,Rutaceae,Sapindales,Citrus,"{'calories': 45, 'fat': 0.4, 'sugar': 9.1, 'ca..."
27,Pitahaya,78,Cactaceae,Caryophyllales,Cactaceae,"{'calories': 36, 'fat': 0.4, 'sugar': 3.0, 'ca..."
28,Lime,44,Rutaceae,Sapindales,Citrus,"{'calories': 25, 'fat': 0.1, 'sugar': 1.7, 'ca..."
29,Pomegranate,79,Lythraceae,Myrtales,Punica,"{'calories': 83, 'fat': 1.2, 'sugar': 13.7, 'c..."
30,Dragonfruit,80,Cactaceae,Caryophyllales,Selenicereus,"{'calories': 60, 'fat': 1.5, 'sugar': 8.0, 'ca..."
31,Grape,81,Vitaceae,Vitales,Vitis,"{'calories': 69, 'fat': 0.16, 'sugar': 16.0, '..."
32,Morus,82,Moraceae,Rosales,Morus,"{'calories': 43, 'fat': 0.39, 'sugar': 8.1, 'c..."
33,Feijoa,76,Myrtaceae,Myrtoideae,Sellowiana,"{'calories': 44, 'fat': 0.4, 'sugar': 3.0, 'ca..."
34,Avocado,84,Lauraceae,Laurales,Persea,"{'calories': 160, 'fat': 14.66, 'sugar': 0.66,..."
35,Kiwifruit,85,Actinidiaceae,Ericales,Actinidia,"{'calories': 61, 'fat': 0.5, 'sugar': 8.9, 'ca..."
36,Cranberry,87,Ericaceae,Ericales,Vaccinium,"{'calories': 46, 'fat': 0.1, 'sugar': 4.0, 'ca..."
37,Cherry,9,Rosaceae,Rosales,Prunus,"{'calories': 50, 'fat': 0.3, 'sugar': 8.0, 'ca..."
38,Peach,86,Rosaceae,Rosales,Prunus,"{'calories': 39, 'fat': 0.25, 'sugar': 8.4, 'c..."
39,Jackfruit,94,Moraceae,Rosales,Artocarpus,"{'calories': 95, 'fat': 0.0, 'sugar': 19.1, 'c..."
40,Horned Melon,95,Cucurbitaceae,Cucurbitales,Cucumis,"{'calories': 44, 'fat': 1.26, 'sugar': 0.5, 'c..."
41,Hazelnut,96,Betulaceae,Fagales,Corylus,"{'calories': 628, 'fat': 61.0, 'sugar': 4.3, '..."
42,Pomelo,98,Rutaceae,Sapindales,Citrus,"{'calories': 37, 'fat': 0.0, 'sugar': 8.5, 'ca..."
43,Mangosteen,99,Clusiaceae,Malpighiales,Garcinia,"{'calories': 73, 'fat': 0.58, 'sugar': 16.11, ..."
44,Pumpkin,100,Cucurbitaceae,Cucurbitales,Cucurbita,"{'calories': 25, 'fat': 0.3, 'sugar': 3.3, 'ca..."
45,Japanese Persimmon,101,Ebenaceae,Ericales,Diospyros,"{'calories': 70, 'fat': 0.2, 'sugar': 13.0, 'c..."
46,Papaya,42,Caricaceae,Brassicales,Carica,"{'calories': 39, 'fat': 0.3, 'sugar': 4.4, 'ca..."
47,Annona,103,Annonaceae,Rosales,Annonas,"{'calories': 92, 'fat': 0.29, 'sugar': 3.4, 'c..."
48,Ceylon Gooseberry,104,Salicaceae,Malpighiales,Dovyalis,"{'calories': 47, 'fat': 0.3, 'sugar': 8.1, 'ca..."

The result is in a nested json format. The 'nutrition' column contains multiple subcolumns, so the data needs to be 'flattened' or normalized.

In [ ]:
df2 = pd.json_normalize(results)

In [ ]:
df2

Let's see if we can extract some information from this dataframe. Perhaps, we need to know the family and genus of a cherry.

In [ ]:
cherry = df2.loc[df2["name"] == 'Cherry']
(cherry.iloc[0]['family']) , (cherry.iloc[0]['genus'])

## Exercise 2
In this Exercise, find out how many calories are contained in a banana.

In [ ]:
# Write your code here

<details><summary>Click here for the solution</summary>

```python
cal_banana = df2.loc[df2["name"] == 'Banana']
cal_banana.iloc[0]['nutritions.calories']
```

</details>

## Exercise 3

This [page](https://mixedanalytics.com/blog/list-actually-free-open-no-auth-needed-apis/) contains a list of free public APIs for you to practice. Let us deal with the following example.

#### Official Joke API 
This API returns random jokes from a database. The following URL can be used to retrieve 10 random jokes.

https://official-joke-api.appspot.com/jokes/ten

1. Using `requests.get("url")` function, load the data from the URL.

In [ ]:
# Write your code here
data = requests.get("https://official-joke-api.appspot.com/jokes/ten")

<details><summary>Click here for the solution</summary>

```python
data2 = requests.get("https://official-joke-api.appspot.com/jokes/ten")
```

</details>

2. Retrieve results using `json.loads()` function.

In [ ]:
# Write your code here

<details><summary>Click here for the solution</summary>

```python
results2 = json.loads(data2.text)
```

</details>

3. Convert json data into *pandas* data frame. Drop the type and id columns.

In [ ]:
# Write your code here

<details><summary>Click here for the solution</summary>

```python
df3 = pd.DataFrame(results2)
df3.drop(columns=["type","id"],inplace=True)
df3
```

</details>

# Congratulations! - You have completed the lab